import _ from "lodash";
import React, { Component } from "react";
import ReactDOM from "react-dom";
import header from "./componenets/header";
import logo from "./components/logo";
import nav from "./components/nav";
import profileStats from "./components/profile_stats";
import rosterProfile from "./components/roster_profile";
import roster from "./components/roster";
import stageSelect from "./components/stage_select";
